# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoDiary' do
  pod 'Firebase/Core'
  pod 'Firebase/Analytics', '4.2.0'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end

